name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.23.5
  - pip=23.0.1
  - pip:
    - azureml-defaults==1.53.0
    - sentence-transformers==3.0.1
    - huggingface-hub==0.24.6
    - python-dotenv==1.0.1
    - accelerate==0.34.0