name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.23.5
  - pip=23.0.1
  - pip:
    - azureml-defaults==1.53.0
    - inference-schema
    - joblib==1.2.0
    - sentence-transformers==3.0.1